- image_file: newimages/multiple-shapes-and-sizes-structure-materials-vector-25729627.jpg
  shapes:
- image_file: newimages/preview.jpg
  shapes:
- image_file: newimages/1-1024x1024.jpg
  shapes:
- image_file: newimages/istockphoto-1253060480-1024x1024.jpg
  shapes:
